import numpy as np
import math

class MLP:

    """
    Constructor: Computes MLP.

    Args:
        inputLayer (int): size of input
        hiddenLayer (int): size of hidden layer.
        outputLayer (int): size of output layer
        seed (scalar): seed of the random numeric.
        epislom (scalar) : random initialization range. e.j: 1 = [-1..1], 2 = [-2,2]...
    """

    def __init__(self,inputLayer,hidenLayer, outputLayer, seed=0, epislom = 0.12):
        np.random.seed(seed)

        self.inputLayer = inputLayer
        self.hiddenLayer = hidenLayer
        self.outputLayer = outputLayer
        self.eps = epislom
        
        # Inicialización aleatoria en [-eps, eps]
        self.theta1 = np.random.uniform(
            -self.eps, self.eps, (hidenLayer, inputLayer + 1)
        )
        self.theta2 = np.random.uniform(
            -self.eps, self.eps, (outputLayer, hidenLayer + 1)
        )

        """
    Reset the theta matrix created in the constructor by both theta matrix manualy loaded.

    Args:
        theta1 (array_like): Weights for the first layer in the neural network.
        theta2 (array_like): Weights for the second layer in the neural network.
    """
    def new_trained(self,theta1,theta2):
        self.theta1 = theta1
        self.theta2 = theta2
        
    """
    Num elements in the training data. (private)

    Args:
        x (array_like): input data. 
    """
    def _size(self,x):
        return x.shape[0]
    
    """
    Computes de sigmoid function of z (private)

    Args:
        z (array_like): activation signal received by the layer.
    """
    def _sigmoid(self,z):
        z = np.asarray(z)
        return 1 / (1 + np.exp(-z))

    """
    Computes de sigmoid derivation of de activation (private)

    Args:
        a (array_like): activation received by the layer.
    """   
    def _sigmoidPrime(self,a):
        a = np.asarray(a)
        return a * (1.0 - a)

    """
    Run the feedwordwar neural network step

    Args:
        x (array_like): input of the neural network.

	Return 
	------
	a1,a2,a3 (array_like): activation functions of each layers
    z2,z3 (array_like): signal fuction of two last layers
    """
    def feedforward(self,x):
        m = self._size(x)

        # capa de entrada con sesgo
        a1 = np.hstack([np.ones((m, 1)), x])            # (m, 401)

        # capa oculta
        z2 = a1 @ self.theta1.T                         # (m, 25)
        a2_no_bias = self._sigmoid(z2)                  # (m, 25)
        a2 = np.hstack([np.ones((m,1)), a2_no_bias])    # (m, 26)

        # capa de salida
        z3 = a2 @ self.theta2.T                         # (m, 10)
        a3 = self._sigmoid(z3)                          # (m, 10)

        return a1,a2,a3,z2,z3


    """
    Computes only the cost of a previously generated output (private)

    Args:
        yPrime (array_like): output generated by neural network.
        y (array_like): output from the dataset
        lambda_ (scalar): regularization parameter

	Return 
	------
	J (scalar): the cost.
    """
    def compute_cost(self, yPrime,y, lambda_):
        yPrime = np.asarray(yPrime)
        y = np.asarray(y)

        m = y.shape[0]
        eps = 1e-8

        # Coste de entropía cruzada multi-clase
        J = -(1.0 / m) * np.sum(
            y * np.log(yPrime + eps) + (1 - y) * np.log(1 - yPrime + eps)
        )

        # Añadimos regularización L2
        J += self._regularizationL2Cost(m, lambda_)
        return J
    

    """
    Get the class with highest activation value

    Args:
        a3 (array_like): output generated by neural network.

	Return 
	------
	p (scalar): the class index with the highest activation value.
    """
    def predict(self,a3):
        a3 = np.asarray(a3)
        # Devolvemos directamente el índice [0..9]
        p = np.argmax(a3, axis=1)
        return p
    

    """
    Compute the gradients of both theta matrix parámeters and cost J

    Args:
        x (array_like): input of the neural network.
        y (array_like): output of the neural network.
        lambda_ (scalar): regularization.

	Return 
	------
	J: cost
    grad1, grad2: the gradient matrix (same shape than theta1 and theta2)
    """
    def compute_gradients(self, x, y, lambda_):
        x = np.asarray(x)
        y = np.asarray(y)
        m = x.shape[0]

        # Forward
        a1, a2, a3, z2, z3 = self.feedforward(x)

        # Coste de regularización
        J = self.compute_cost(a3, y, lambda_)

        # Backpropagation vectorizado
        delta3 = a3 - y                         # (m, num_labels)
        delta2_full = delta3 @ self.theta2      # (m, hidden+1)
        delta2 = delta2_full[:,1:] * self._sigmoidPrime(a2[:,1:]) # quitamos el sesgo

        # Acumulación de gradientes
        Delta1 = delta2.T @ a1                  # (hidden, input+1)
        Delta2 = delta3.T @ a2                  # (output, hidden+1)

        grad1 = Delta1 / m
        grad2 = Delta2 / m

        # Regularización en gradiente (sin sesgo)
        grad1 += self._regularizationL2Gradient(self.theta1, lambda_, m)
        grad2 += self._regularizationL2Gradient(self.theta2, lambda_, m)

        return (J, grad1, grad2)
    
    """
    Compute L2 regularization gradient

    Args:
        theta (array_like): a theta matrix to calculate the regularization.
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 Gradient value
    """
    def _regularizationL2Gradient(self, theta, lambda_, m):
        reg = np.zeros_like(theta)
        if lambda_ != 0:
            reg[:,1:] = (lambda_ / m) * theta[:,1:]
        return reg
    
    
    """
    Compute L2 regularization cost

    Args:
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 cost value
    """

    def _regularizationL2Cost(self, m, lambda_):
        if lambda_ == 0:
            return 0.0
        # No se regulariza la columba del sesgo
        reg1 = np.sum(self.theta1[:,1:] ** 2)
        reg2 = np.sum(self.theta2[:,1:] ** 2)
        return (lambda_ / (2.0 * m)) * (reg1 + reg2)
    
    
    def backpropagation(self, x, y, alpha, lambda_, numIte, verbose=0):
        Jhistory = []
        for i in range(numIte):
            J, grad1, grad2 = self.compute_gradients(x, y, lambda_)

            # Actualización de pesos
            self.theta1 -= alpha * grad1
            self.theta2 -= alpha * grad2

            Jhistory.append(J)

            if verbose > 0 :
                if i % verbose == 0 or i == (numIte-1):
                    print(f"Iteration {(i+1):6}: Cost {float(J):8.4f}   ")
        
        return Jhistory
    


"""
target_gradient funcitón of gradient test 1
"""
def target_gradient(input_layer_size,hidden_layer_size,num_labels,x,y,reg_param):
    mlp = MLP(input_layer_size,hidden_layer_size,num_labels)
    J, grad1, grad2 = mlp.compute_gradients(x,y,reg_param)
    return J, grad1, grad2, mlp.theta1, mlp.theta2


"""
costNN funcitón of gradient test 1
"""
def costNN(Theta1, Theta2,x, ys, reg_param):
    mlp = MLP(x.shape[1],1, ys.shape[1])
    mlp.new_trained(Theta1,Theta2)
    J, grad1, grad2 = mlp.compute_gradients(x,ys,reg_param)
    return J, grad1, grad2


"""
mlp_backprop_predict 2 to be execute test 2
"""
def MLP_backprop_predict(X_train,y_train, X_test, alpha, lambda_, num_ite, verbose):
    mlp = MLP(X_train.shape[1],25,y_train.shape[1])
    Jhistory = mlp.backpropagation(X_train,y_train,alpha,lambda_,num_ite,verbose)
    a3= mlp.feedforward(X_test)[2]
    y_pred=mlp.predict(a3)
    return y_pred